create table insert01 (
  a int, 
  b float, 
  c double,
  d char(10),
  e varchar (10),
  f BIT,
  g BIT VARYING,
  h timestamp,
  i timestamptz,
  j datetime,
  k datetimetz,
  l date, 
  m time, 
  n BLOB,
  o CLOB,
  p numeric(10,5),
  q enum ('cdc', 'cdc2', 'cdc3'));
